version: '3.4'

services:
  rewriter_api:
    image: ${DOCKER_REGISTRY-}rewriterapi
    build:
      context: .
      dockerfile: rewriter/Dockerfile
    depends_on:
      - rewriter_sqlserver
    env_file:
      - env.api

  rewriter_sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - env.api
    ports:
      - "1433:1433"